"""add username field to User model

Revision ID: 03a5a645bbb6
Revises: 
Create Date: 2026-04-20 15:50:32.061347

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '03a5a645bbb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
